### ISSUE TITLE
NotionAPI 관련 오류 질문드립니다..

### ISSUE THREAD

**Issue by reo91004** [2skydev/Notion-Next.js-blog-starter-kit#64]
```
NotionAPI getSignedfileUrls error HTTPError: Response code 500 (Internal Server Error)
--
16:24:32.366 | at Request.<anonymous> (file:///vercel/path0/node_modules/got/dist/source/as-promise/index.js:86:42)
16:24:32.366 | at Object.onceWrapper (node:events:633:26)
16:24:32.366 | at Request.emit (node:events:530:35)
16:24:32.366 | at Request._onResponseBase (file:///vercel/path0/node_modules/got/dist/source/core/index.js:697:22)
16:24:32.366 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
16:24:32.366 | at async Request._onResponse (file:///vercel/path0/node_modules/got/dist/source/core/index.js:736:13) {
16:24:32.366 | input: undefined,
16:24:32.366 | code: 'ERR_NON_2XX_3XX_RESPONSE',
16:24:32.366 | timings: {
16:24:32.366 | start: 1717313072253,
16:24:32.366 | socket: 1717313072253,
16:24:32.366 | lookup: 1717313072253,
16:24:32.366 | connect: 1717313072253,
16:24:32.367 | secureConnect: 1717313072253,
16:24:32.367 | upload: 1717313072254,
16:24:32.367 | response: 1717313072360,
16:24:32.367 | end: 1717313072361,
16:24:32.367 | error: undefined,
16:24:32.367 | abort: undefined,
16:24:32.367 | phases: {
16:24:32.367 | wait: 0,
16:24:32.367 | dns: 0,
16:24:32.367 | tcp: 0,
16:24:32.367 | tls: 0,
16:24:32.367 | request: 1,
16:24:32.367 | firstByte: 106,
16:24:32.367 | download: 1,
16:24:32.367 | total: 108
16:24:32.367 | }
16:24:32.367 | },
16:24:32.367 | options: {
16:24:32.367 | request: undefined,
16:24:32.367 | agent: { http: undefined, https: undefined, http2: undefined },
16:24:32.367 | h2session: undefined,
16:24:32.367 | decompress: true,
16:24:32.367 | timeout: {
16:24:32.367 | connect: undefined,
16:24:32.367 | lookup: undefined,
16:24:32.367 | read: undefined,
16:24:32.367 | request: undefined,
16:24:32.367 | response: undefined,
16:24:32.367 | secureConnect: undefined,
16:24:32.367 | send: undefined,
16:24:32.367 | socket: undefined
16:24:32.367 | },
16:24:32.367 | prefixUrl: '',
16:24:32.368 | body: '{"urls":[{"permissionRecord":{"table":"block","id":"122a0ba0-7797-45ba-9577-4d051564708c"},"url":"/images/page-cover/rijksmuseum_jan_lievens_1627.jpg"}]}',
16:24:32.368 | form: undefined,
16:24:32.368 | json: undefined,
16:24:32.368 | cookieJar: undefined,
16:24:32.368 | ignoreInvalidCookies: false,
16:24:32.368 | searchParams: undefined,
16:24:32.368 | dnsLookup: undefined,
16:24:32.368 | dnsCache: undefined,
16:24:32.368 | context: {},
16:24:32.368 | hooks: {
16:24:32.368 | init: [],
16:24:32.368 | beforeRequest: [],
16:24:32.368 | beforeError: [],
16:24:32.368 | beforeRedirect: [],
16:24:32.368 | beforeRetry: [],
16:24:32.368 | afterResponse: []
16:24:32.368 | },
16:24:32.368 | followRedirect: true,
16:24:32.368 | maxRedirects: 10,
16:24:32.368 | cache: undefined,
16:24:32.368 | throwHttpErrors: true,
16:24:32.368 | username: '',
16:24:32.368 | password: '',
16:24:32.368 | http2: false,
16:24:32.368 | allowGetBody: false,
16:24:32.368 | headers: {
16:24:32.368 | 'user-agent': 'got (https://github.com/sindresorhus/got)',
16:24:32.369 | 'content-type': 'application/json',
16:24:32.369 | accept: 'application/json',
16:24:32.369 | 'content-length': '153',
16:24:32.369 | 'accept-encoding': 'gzip, deflate, br'
16:24:32.369 | },
16:24:32.369 | methodRewriting: false,
16:24:32.369 | dnsLookupIpVersion: undefined,
16:24:32.369 | parseJson: [Function: parse],
16:24:32.369 | stringifyJson: [Function: stringify],
16:24:32.369 | retry: {
16:24:32.369 | limit: 2,
16:24:32.369 | methods: [ 'POST' ],
16:24:32.369 | statusCodes: [
16:24:32.369 | 408, 413, 429, 500,
16:24:32.369 | 502, 503, 504, 521,
16:24:32.369 | 522, 524
16:24:32.369 | ],
16:24:32.369 | errorCodes: [
16:24:32.369 | 'ETIMEDOUT',
16:24:32.369 | 'ECONNRESET',
16:24:32.369 | 'EADDRINUSE',
16:24:32.369 | 'ECONNREFUSED',
16:24:32.369 | 'EPIPE',
16:24:32.369 | 'ENOTFOUND',
16:24:32.369 | 'ENETUNREACH',
16:24:32.370 | 'EAI_AGAIN'
16:24:32.370 | ],
16:24:32.370 | maxRetryAfter: undefined,
16:24:32.370 | calculateDelay: [Function: calculateDelay],
16:24:32.370 | backoffLimit: Infinity,
16:24:32.370 | noise: 100
16:24:32.370 | },
16:24:32.370 | localAddress: undefined,
16:24:32.370 | method: 'POST',
16:24:32.370 | createConnection: undefined,
16:24:32.371 | cacheOptions: {
16:24:32.371 | shared: undefined,
16:24:32.371 | cacheHeuristic: undefined,
16:24:32.371 | immutableMinTimeToLive: undefined,
16:24:32.371 | ignoreCargoCult: undefined
16:24:32.371 | },
16:24:32.371 | https: {
16:24:32.371 | alpnProtocols: undefined,
16:24:32.371 | rejectUnauthorized: undefined,
16:24:32.371 | checkServerIdentity: undefined,
16:24:32.371 | certificateAuthority: undefined,
16:24:32.371 | key: undefined,
16:24:32.371 | certificate: undefined,
16:24:32.371 | passphrase: undefined,
16:24:32.371 | pfx: undefined,
16:24:32.371 | ciphers: undefined,
16:24:32.371 | honorCipherOrder: undefined,
16:24:32.371 | minVersion: undefined,
16:24:32.371 | maxVersion: undefined,
16:24:32.371 | signatureAlgorithms: undefined,
16:24:32.371 | tlsSessionLifetime: undefined,
16:24:32.371 | dhparam: undefined,
16:24:32.371 | ecdhCurve: undefined,
16:24:32.372 | certificateRevocationLists: undefined
16:24:32.372 | },
16:24:32.372 | encoding: undefined,
16:24:32.372 | resolveBodyOnly: false,
16:24:32.372 | isStream: false,
16:24:32.372 | responseType: 'text',
16:24:32.372 | url: URL {
16:24:32.372 | href: 'https://www.notion.so/api/v3/getSignedFileUrls',
16:24:32.372 | origin: 'https://www.notion.so',
16:24:32.372 | protocol: 'https:',
16:24:32.372 | username: '',
16:24:32.372 | password: '',
16:24:32.372 | host: 'www.notion.so',
16:24:32.372 | hostname: 'www.notion.so',
16:24:32.372 | port: '',
16:24:32.372 | pathname: '/api/v3/getSignedFileUrls',
16:24:32.372 | search: '',
16:24:32.372 | searchParams: URLSearchParams {},
16:24:32.372 | hash: ''
16:24:32.372 | },
16:24:32.372 | pagination: {
16:24:32.372 | transform: [Function: transform],
16:24:32.373 | paginate: [Function: paginate],
16:24:32.373 | filter: [Function: filter],
16:24:32.373 | shouldContinue: [Function: shouldContinue],
16:24:32.373 | countLimit: Infinity,
16:24:32.373 | backoff: 0,
16:24:32.373 | requestLimit: 10000,
16:24:32.373 | stackAllItems: false
16:24:32.373 | },
16:24:32.373 | setHost: true,
16:24:32.373 | maxHeaderSize: undefined
16:24:32.373 | }
16:24:32.373 | }
```

vercel에 배포할 시 이런 오류가 엄청 많이 나는데 어떻게 해결하는지 알 수 있을까요..?

**Comment by reo91004** [comment]
이미지 불러오는 API 관련 이슈인거로 확인했습니다.
